Repository handsontable/hyperformula, pull requests merged in 2023-03, with the labels that each got.

#1170 Docs: Edit 2.3.1 docs
  CHANGELOG.md
  docs/guide/built-in-functions.md
  docs/guide/custom-functions.md
  docs/guide/named-expressions.md
  docs/guide/release-notes.md
  docs/guide/types-of-values.md
  src/HyperFormula.ts
  src/NamedExpressions.ts
  src/SimpleRangeValue.ts
  src/interpreter/plugin/FunctionPlugin.ts
  test/emitting-events.spec.ts
Labels: Docs

#1182 Fix typo in code snippet in the `advanced-usage` guide
  docs/guide/advanced-usage.md
Labels: Bug, Docs, CLA signed

#875 Added support for infering return types
  CHANGELOG.md
  src/BuildEngineFactory.ts
  src/CellContentParser.ts
  src/interpreter/FunctionRegistry.ts
  src/interpreter/Interpreter.ts
  src/interpreter/plugin/FunctionPlugin.ts
  src/interpreter/plugin/MatrixPlugin.ts
  test/infer-return-types.spec.ts
Labels: CLA signed

#1192 Wrap naked throw statements in `Error` class in `ArrayValue.ts`
  src/ArrayValue.ts
Labels: CLA signed

#1204 Linter: Disallow literal (non Error-wrapped) throws
  .eslintrc.js
  src/DependencyGraph/ValueCellVertex.ts
  src/LazilyTransformingAstService.ts
  src/NamedExpressions.ts
  src/UndoRedo.ts
Labels: CLA signed

#1209 Add missing unit tests for errors and exceptions
  test/config.spec.ts
  test/cruds/adding-columns.spec.ts
  test/cruds/copy-paste.spec.ts
  test/i18n.spec.ts
  test/named-expressions.spec.ts
  test/parser/parser.spec.ts
  test/undo-redo.spec.ts
Labels: CLA signed

#1200 Code Coverage: Improve coverage for src/dependencyTransformers (95.43% -> 97.31%)
  test/dependencyTransformers/clean-out-of-scope-dependencies-transformer.spec.ts
  test/dependencyTransformers/combined-transformer.spec.ts
  test/dependencyTransformers/remove-columns-transformer.spec.ts
  test/dependencyTransformers/remove-rows-transformer.spec.ts
  test/dependencyTransformers/transformer.spec.ts
Labels: CLA signed

#1218 Code Coverage: Improve coverage for HyperFormula.ts (92.38% -> 99.65%)
  src/HyperFormula.ts
  test/cruds/change-cell-content.spec.ts
  test/cruds/copy-paste.spec.ts
  test/cruds/cut-paste.spec.ts
  test/cruds/move-cells.spec.ts
  test/engine.spec.ts
  test/graph-dependencies-queries.spec.ts
  test/named-expressions.spec.ts
  test/temporary-formulas.spec.ts
  test/undo-redo.spec.ts
Labels: CLA signed
