Repository handsontable/hyperformula, pull requests merged in 2024-12, with the labels that each got.

#1414 Add XLOOKUP without support for non standard match_mode and search_mode - and returning values/arrays instead of ranges
  docs/guide/built-in-functions.md
  src/i18n/languages/csCZ.ts
  src/i18n/languages/daDK.ts
  src/i18n/languages/deDE.ts
  src/i18n/languages/enGB.ts
  src/i18n/languages/esES.ts
  src/i18n/languages/fiFI.ts
  src/i18n/languages/frFR.ts
  src/i18n/languages/huHU.ts
  src/i18n/languages/itIT.ts
  src/i18n/languages/nbNO.ts
  src/i18n/languages/nlNL.ts
  src/i18n/languages/plPL.ts
  src/i18n/languages/ptPT.ts
  src/i18n/languages/ruRU.ts
  src/i18n/languages/svSE.ts
  src/i18n/languages/trTR.ts
  src/interpreter/plugin/LookupPlugin.ts
  test/interpreter/function-xlookup.spec.ts
Labels: CLA signed

#1470 Docs: Fix exceljs API usage in the file import code example to handle shared formulas
  docs/guide/file-import.md
Labels: Bug, Docs, Impact: Low

#1476 Docs: Explain `getSheetDimensions()` issue with empty rows and columns
  src/HyperFormula.ts
Labels: Docs, Impact: Low
